// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oermbvjdjkihizpagobp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lcm1idmpkamtpaGl6cGFnb2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3ODM3MDEsImV4cCI6MjA1NTM1OTcwMX0.d-Jg55sA8VaPqRTCcmQipAMQLMc5aB-9jejc21WGVBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);